kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: chrispruitt
      password:
        from_secret: docker_password
      repo: ${DRONE_REPO}
      tags: latest
      squash: true
      auto_tag: true
      cache_from:
        - "${DRONE_REPO}:latest"
